"""Domain events and the event bus abstraction."""

from aeris.events.bus import EventBus, EventHandler, InMemoryEventBus
from aeris.events.events import (
    CandidateEscalated,
    DecisionCompleted,
    DecisionRequested,
    DetectionCreated,
    DetectionUpdated,
    DomainEvent,
    DroneDisconnected,
    DroneLinkStateChanged,
    DroneRegistered,
    DroneReturning,
    HumanReviewRequested,
    MissionAborted,
    MissionCompleted,
    MissionCreated,
    MissionPaused,
    MissionResumed,
    MissionStarted,
    OperatorActionReceived,
    SafetyOverrideTriggered,
    SurvivorConfirmed,
    SurvivorRejected,
    TelemetryReceived,
    ZoneAssigned,
    ZoneCoverageUpdated,
    ZoneReassignmentRequested,
    ZoneStatusChanged,
)

__all__ = [
    "CandidateEscalated",
    "DecisionCompleted",
    "DecisionRequested",
    "DetectionCreated",
    "DetectionUpdated",
    "DomainEvent",
    "DroneDisconnected",
    "DroneLinkStateChanged",
    "DroneRegistered",
    "DroneReturning",
    "EventBus",
    "EventHandler",
    "HumanReviewRequested",
    "InMemoryEventBus",
    "MissionAborted",
    "MissionCompleted",
    "MissionCreated",
    "MissionPaused",
    "MissionResumed",
    "MissionStarted",
    "OperatorActionReceived",
    "SafetyOverrideTriggered",
    "SurvivorConfirmed",
    "SurvivorRejected",
    "TelemetryReceived",
    "ZoneAssigned",
    "ZoneCoverageUpdated",
    "ZoneReassignmentRequested",
    "ZoneStatusChanged",
]
